yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('posts/<int:post_id>/', views.post_view, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf.urls import handler403
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        'Текст поста', help_text='Введите текст поста.'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='posts', verbose_name='Автор поста')
    group = models.ForeignKey(
        'Group', on_delete=models.SET_NULL,
        blank=True, null=True, related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу для поста (не обязательно)'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Можете добавить картинку'
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:15]


class Group(models.Model):
    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField('Адрес', unique=True)
    description = models.TextField('Описание сообщества')

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        related_name='comments'
    )
    created = models.DateTimeField('Дата комментария', auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Прокомментируйте статью'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User, related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User, related_name='following',
        on_delete=models.CASCADE
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author', ],
                name="unique_constraint",
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_func


@cache_page(20)
def index(request):
    posts = Post.objects.select_related('group').all()
    page_obj = paginator_func(request, posts)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_func(request, posts)
    return render(
        request, 'posts/group_list.html',
        {'group': group, 'page_obj': page_obj})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginator_func(request, posts)
    following = False
    if request.user.is_authenticated:
        following = (
            Follow.objects.filter(user=request.user, author=author).exists()
        )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'comments': comments,
        'post': post,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    return render(
        request, 'posts/post_create.html',
        {'form': form}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_func(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return redirect('posts:profile', request.user.username)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = get_object_or_404(Follow, user=request.user, author=author)
    follow.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Мои подписки{% endblock %}
{% block header %}Мои подписки{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  <div class="container py-5">
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
        </ul>
        {% thumbnail post.image "100x100" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы: {{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Записи сообщества: {{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
        </ul>
        {% thumbnail post.image "100x100" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </article>
      <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы: {{ post.group.title }}</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  <div class="container py-5">
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
        </ul>
        {% thumbnail post.image "100x100" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы: {{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}{% if form.instance.id %}Редактирование записи{% else %}Новая запись{% endif %}{% endblock %}
{% block header %}{% if form.instance.id %}Редактирование записи{% else %}Новая запись{% endif %}{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-10 p-5">
        <div class="card">
          <div class="card-header">
            {% if form.instance.id %}Редактирование записи{% else %}Новая запись{% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data" action={% if form.instance.id %} "{% url 'posts:post_edit' form.instance.id %}" {% else %} "{% url 'posts:post_create' %}" {% endif %} >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row" aria-required="{{ field.field.required }}">
                  <label
                    for="{{ field.id_for_label }}"
                    class="col-md-4 col-form-label text-md-right">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required">*</span>
                    {% endif %}
                  </label>
                  <div class="col-md-6">
                    {{ field|addclass:"form-control" }}
                    {% if field.help_text %}
                      <small
                        id="{{ field.id_for_label }}-help"
                        class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if form.instance.id %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title}}<br>
              <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "300x300" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
        <hr>
        {% include "includes/comments.html" %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ author.get_full_name }} профайл пользователя{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
          </li>
        </ul>
        {% thumbnail post.image "100x100" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы: {{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}